# Numpy

## Importing Package

In [86]:
import numpy as np

## Numpy Arrays

### 1D Array

In [87]:
a = np.array([1,2,3])

In [88]:
print(type(a)) # prints type of array
print(a) # prints the array
print(len(a)) # prints length of an array
print(a.size) # prints number of elements in an array
print(a.itemsize) # prints byte size of an array
print(a.shape) # prints shape of an array
print(a.ndim) # prints dimension of an array
print(a.dtype) # prints data type of an array

<type 'numpy.ndarray'>
[1 2 3]
3
3
8
(3,)
1
int64


In [89]:
a = np.array([1,2,3], dtype = float)

In [90]:
print(type(a)) # prints type of array
print(a) # prints the array
print(len(a)) # prints length of an array
print(a.size) # prints number of elements in an array
print(a.itemsize) # prints byte size of an array
print(a.shape) # prints shape of an array
print(a.ndim) # prints dimension of an array
print(a.dtype) # prints data type of an array

<type 'numpy.ndarray'>
[1. 2. 3.]
3
3
8
(3,)
1
float64


In [91]:
a[1] = 5.33 # replace value of element:2 at index:1 in array 'a'
print(a)

[1.   5.33 3.  ]


In [92]:
a = a.astype(np.int32) # covert an array into INT 32bits
print(a) # prints array

[1 5 3]


### 2D Array

In [93]:
 a = np.array([(1,2,3), (4,5,6)])

In [94]:
print(type(a)) # prints type of array
print(a) # prints the array
print(len(a)) # prints length of an array
print(a.size) # prints number of elements in an array
print(a.itemsize) # prints byte size of an array
print(a.shape) # prints shape of an array
print(a.ndim) # prints dimension of an array
print(a.dtype) # prints data type of an array

<type 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
2
6
8
(2, 3)
2
int64


In [95]:
 a = np.array([(1,2,3.56), (4,5,6)], dtype = float)

In [96]:
print(type(a)) # prints type of array
print("\n")
print(a) # prints the array
print("\n")
print(len(a)) # prints length of an array
print("\n")
print(a.size) # prints number of elements in an array
print("\n")
print(a.itemsize) # prints byte size of an array
print("\n")
print(a.shape) # prints shape of an array
print("\n")
print(a.ndim) # prints dimension of an array
print("\n")
print(a.dtype) # prints data type of an array
print("\n")

<type 'numpy.ndarray'>


[[1.   2.   3.56]
 [4.   5.   6.  ]]


2


6


8


(2, 3)


2


float64




In [97]:
print(a[0,2])
print("\n")
print(a[1,2])

3.56


6.0


In [98]:
a = a.astype(np.int32) # covert an array into INT 32bits
print(a) # prints array

[[1 2 3]
 [4 5 6]]


In [99]:
a = a.reshape(3,2) #reshaping an array
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [100]:
print(a[0,1]) # prints element at index 0,1

2


In [101]:
print(a[0:,1]) # prints every row elements at index (rowIndex,1)
print("\n")
print(a[0:2,1]) # prints row 0 to row 1 elements at index (rowIndex,1)

[2 4 6]


[2 4]


### Placeholders

In [102]:
a = np.zeros((3,4)) # Create an array of zeros
print(a)
print("\n")
b = np.ones((2,3,4),dtype=np.int16) # Create an array of ones
print(b)
print("\n")
c = np.arange(10,25,5) # Create an array of evenly spaced values (step value)  
print(c)
print("\n")
d = np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)
print(d)
print("\n")
e = np.full((2,2),7) # Create a constant array
print(e)
print("\n")
f = np.eye(2) # Create a 2X2 identity matrix
print(f)
print("\n")
g = np.random.random((2,2)) # Create an array with random values
print(g)
print("\n")
h = np.empty((3,2)) # Create an empty array
print(h)
print("\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


[10 15 20]


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


[[7 7]
 [7 7]]


[[1. 0.]
 [0. 1.]]


[[0.40380429 0.8149315 ]
 [0.77218471 0.77736521]]


[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]




### Numpy Operations

In [103]:
a = np.array([(1,2,3), (4,5,6)], dtype = float)
print(a)
print("\n")
b = np.array([(7,8,9), (10,11,12)], dtype = float)
print(b)
print("\n")

[[1. 2. 3.]
 [4. 5. 6.]]


[[ 7.  8.  9.]
 [10. 11. 12.]]




In [104]:
print(a+b)
print("\n")
print(a-b)
print("\n")
print(a/b)
print("\n")
print(a*b)

[[ 8. 10. 12.]
 [14. 16. 18.]]


[[-6. -6. -6.]
 [-6. -6. -6.]]


[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


[[ 7. 16. 27.]
 [40. 55. 72.]]


In [105]:
print(np.add(a, b))
print("\n")
print(np.subtract(a, b))
print("\n")
print(np.divide(a, b))
print("\n")
print(np.multiply(a, b))
print("\n")
print("*********************************")
e = b.reshape(3,2)
print(e)
print("\n")
print(a)
print("\n")
print(e.dot(a)) # Can also use np.dot(e,a)
print("\n")
print(np.cross(a,b))

[[ 8. 10. 12.]
 [14. 16. 18.]]


[[-6. -6. -6.]
 [-6. -6. -6.]]


[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


[[ 7. 16. 27.]
 [40. 55. 72.]]


*********************************
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]


[[1. 2. 3.]
 [4. 5. 6.]]


[[ 39.  54.  69.]
 [ 49.  68.  87.]
 [ 59.  82. 105.]]


[[-6. 12. -6.]
 [-6. 12. -6.]]


In [106]:
print(a)
print("\n")
print(a.max())
print("\n")
print(a.min())
print("\n")
print(a.sum())
print("\n")
print(a.sum(axis = 0))
print("\n")
print(a.sum(axis = 1))
print("\n")

[[1. 2. 3.]
 [4. 5. 6.]]


6.0


1.0


21.0


[5. 7. 9.]


[ 6. 15.]




In [107]:
print(a)
print("\n")
print(b)
print("\n")
print("****************************")
print(np.exp(b))                          #Exponentiation
print("\n")
print(np.sqrt(b))                         #Square root
print("\n")
print(np.sin(a))                          #Print sines of an array
print("\n")
print(np.cos(b))                          #Element-wise cosine 
print("\n")
print(np.log(a))                          #Element-wise natural logarithm                           
print("\n")

[[1. 2. 3.]
 [4. 5. 6.]]


[[ 7.  8.  9.]
 [10. 11. 12.]]


****************************
[[  1096.63315843   2980.95798704   8103.08392758]
 [ 22026.46579481  59874.1417152  162754.791419  ]]


[[2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162]]


[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


[[ 0.75390225 -0.14550003 -0.91113026]
 [-0.83907153  0.0044257   0.84385396]]


[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]




In [108]:
x = np.array([1,2,3])

print(np.median(x))                  #Median
print("\n")
print(np.corrcoef(x))                #Correlation coefficient
print("\n")
print(np.std(x))                     #Standard deviation
print("\n")

y = np.copy(x)                       #Copy array to y
print(y)

2.0


1.0


0.816496580927726


[1 2 3]


### Array Manupulation

In [109]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype = int)
print(a)
print("\n")

### Transpose
t = np.transpose(a)
print(t)
print("\n")

### Reshape
ra = a.ravel()
print(ra)
print("\n")

### Modify
print(np.append(ra,33))
print(np.insert(ra, 5, 55))
print(np.delete(ra,[8]))
print("\n")

### Combine
b = np.array([10,11,12], dtype = int)
print(np.concatenate((ra,b),axis=0))
print("\n")

### Split
print(np.hsplit(ra,3))
print("\n")
a = np.array([(1,2,3), (4,5,6), (7,8,9), (10,11,12)], dtype = int)
print(np.vsplit(a,2))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


[1 2 3 4 5 6 7 8 9]


[ 1  2  3  4  5  6  7  8  9 33]
[ 1  2  3  4  5 55  6  7  8  9]
[1 2 3 4 5 6 7 8]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
